In [1]:
import numpy as np

In [2]:
arr = np.zeros((2,5))

In [3]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
x = [[1,2,3,4],[3,5,6,7],[0,1,3,4]]

In [5]:
x

[[1, 2, 3, 4], [3, 5, 6, 7], [0, 1, 3, 4]]

In [6]:
ar=np.array(x)

In [7]:
ar

array([[1, 2, 3, 4],
       [3, 5, 6, 7],
       [0, 1, 3, 4]])

In [8]:
ar.sum(axis=0)

array([ 4,  8, 12, 15])

In [9]:
ar.sum(axis=1)

array([10, 21,  8])

In [10]:
ar.T

array([[1, 3, 0],
       [2, 5, 1],
       [3, 6, 3],
       [4, 7, 4]])

In [11]:
ar.flat

In [12]:
for item in ar.flat:
    print(item + 1)

2
3
4
5
4
6
7
8
1
2
4
5


In [13]:
ar.ndim

2

In [14]:
ar.size

12

In [15]:
ar.nbytes

96

In [16]:
one = np.array([1,2,3,4,5,6])

In [17]:
one.argmax()

np.int64(5)

In [18]:
one.argmin()

np.int64(0)

In [19]:
one.argsort()

array([0, 1, 2, 3, 4, 5])

In [20]:
ar

array([[1, 2, 3, 4],
       [3, 5, 6, 7],
       [0, 1, 3, 4]])

In [21]:
ar.argsort()

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [22]:
arr.argmax()

np.int64(0)

In [23]:
ar.argmax()

np.int64(7)

In [24]:
ar.argmax(axis=1)

array([3, 3, 3])

In [25]:
arr.ravel()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
arr.reshape(10,1)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [30]:
ar.min()

np.int64(0)

In [31]:
ar.sum()

np.int64(39)

In [32]:
np.where(ar>6)

(array([1]), array([3]))

In [34]:
np.count_nonzero(ar)

np.int64(11)

In [35]:
np.nonzero(ar)

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2]),
 array([0, 1, 2, 3, 0, 1, 2, 3, 1, 2, 3]))

In [36]:
ar[1,2]=0

In [38]:
np.nonzero(ar)

(array([0, 0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 3, 1, 2, 3]))

In [39]:
import sys

In [40]:
print(sys.version)

3.14.7 (tags/v3.14.7:823f032, Aug  5 2026, 10:51:32) [MSC v.1944 64 bit (AMD64)]


In [41]:
print(sys.argv)

['C:\\Users\\Computer Hospital\\AppData\\Local\\Python\\pythoncore-3.14-64\\Lib\\site-packages\\ipykernel_launcher.py', '-f', 'C:\\Users\\Computer Hospital\\AppData\\Roaming\\jupyter\\runtime\\kernel-a6e9ee94-7945-4784-9778-d34897bacbc0.json']


In [46]:
py_ar = [0,4,54,2]

In [47]:
np_ar = np.array(py_ar)

In [48]:
sys.getsizeof(1)*len(py_ar)

112

In [50]:
sys.getsizeof(1)

28

In [51]:
np_ar.itemsize*np_ar.size

32

In [52]:
np_arr.itemsize

NameError: name 'np_arr' is not defined

In [53]:
np_ar.itemsize

8

In [54]:
np_ar.tolist()

[0, 4, 54, 2]